### ISSUE TITLE
Bullet Reflections too Large

### ISSUE THREAD

**Issue by Frednoeyes** [CiarenceW/FN57-Plugin#8]
The flashlight reflections for the 5.7 cartridges are sized too large, (see photos).
![20230512130238_1](https://github.com/CiarenceW/FN57-Plugin/assets/26194077/14b64821-92ab-4037-9a6e-c287f0cc5da9)
![20230512130547_1](https://github.com/CiarenceW/FN57-Plugin/assets/26194077/67a7a657-3989-4dc5-b783-4a0fbadc80cf)
![20230512125942_1](https://github.com/CiarenceW/FN57-Plugin/assets/26194077/e816ad8b-e394-4a9b-9ea1-456df279a027)

**Comment by CiarenceW** [comment]
god fucking damnit I fucking know why it's like that it's so fucking dumb

**Comment by CiarenceW** [comment]
Fixed by [new version](https://github.com/CiarenceW/FN57-Plugin/releases/tag/v2.2.1). I have no idea how this happened.

**Comment by Frednoeyes** [comment]
Excellent job my good man, real legend of this game.
